In [297]:
import numpy as np
import pandas as pd

df = pd.read_csv("Data/purchased.csv")
df

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0       No 
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [298]:
df.shape

(10, 4)

In [299]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [300]:
x = df.iloc[:,:-1].values

y = df.iloc[:,-1].values
print(x)
print(y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No ' 'Yes' 'No ' 'No ' 'Yes' 'Yes' 'No ' 'Yes' 'No ' 'Yes']


### Xử lý dữ liệu khuyết thiếu bằng giá trị trung bình

In [301]:
from sklearn.impute import SimpleImputer
imputa = SimpleImputer(missing_values = np.nan, strategy='mean')
imputa.fit(x[:,1:3])
x[:,1:3] = imputa.transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Encoding data

In [302]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder = 'passthrough' )
x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [303]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### chuẩn hóa các thuộc tính

In [304]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x[:,3:] = sc.fit_transform(x[:,3:])
x

array([[1.0, 0.0, 0.0, 0.758874361590019, 0.7494732544921677],
       [0.0, 0.0, 1.0, -1.7115038793306814, -1.4381784072687531],
       [0.0, 1.0, 0.0, -1.2755547779917342, -0.8912654918285229],
       [0.0, 0.0, 1.0, -0.1130238410878753, -0.253200423814921],
       [0.0, 1.0, 0.0, 0.17760889313808945, 6.632191985654332e-16],
       [1.0, 0.0, 0.0, -0.5489729424268225, -0.5266568815350361],
       [0.0, 0.0, 1.0, 0.0, -1.0735697969752662],
       [1.0, 0.0, 0.0, 1.3401398300419485, 1.3875383225057696],
       [0.0, 1.0, 0.0, 1.6307725642679132, 1.7521469327992565],
       [1.0, 0.0, 0.0, -0.2583402082008577, 0.29371249162530916]],
      dtype=object)

In [278]:
df = df.dropna()
df

Country   Age   Salary Purchased
0   France  44.0  72000.0       No 
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0       No 
3    Spain  38.0  61000.0       No 
5   France  35.0  58000.0       Yes
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0       No 
9   France  37.0  67000.0       Yes

In [279]:
bool_mapper = {"No ":0,"Yes":1}
df["Purchased"] = df["Purchased"].replace(bool_mapper)
df

C:\Users\Admin-s\AppData\Local\Temp\ipykernel_21980\11030340.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Purchased"] = df["Purchased"].replace(bool_mapper)


Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
5   France  35.0  58000.0          1
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [280]:
df['Age'].min()

27.0

In [281]:
df['Age'].max()

50.0

In [282]:
ages = [25,35,45,55]
age = pd.cut(df['Age'],ages,labels = [0,1,2])
df['Age'] = age
df

C:\Users\Admin-s\AppData\Local\Temp\ipykernel_21980\1847625510.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = age


Country Age   Salary  Purchased
0   France   1  72000.0          0
1    Spain   0  48000.0          1
2  Germany   0  54000.0          0
3    Spain   1  61000.0          0
5   France   0  58000.0          1
7   France   2  79000.0          1
8  Germany   2  83000.0          0
9   France   1  67000.0          1

In [283]:
df['Country'] = df['Country'].astype('category').cat.codes
df

C:\Users\Admin-s\AppData\Local\Temp\ipykernel_21980\65826660.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Country'] = df['Country'].astype('category').cat.codes


Country Age   Salary  Purchased
0        0   1  72000.0          0
1        2   0  48000.0          1
2        1   0  54000.0          0
3        2   1  61000.0          0
5        0   0  58000.0          1
7        0   2  79000.0          1
8        1   2  83000.0          0
9        0   1  67000.0          1

In [284]:
from sklearn.preprocessing import MinMaxScaler

s_scaler = MinMaxScaler()
df_s = s_scaler.fit_transform(pd.DataFrame(df.Salary))

df.Salary = df_s
df

C:\Users\Admin-s\AppData\Local\Temp\ipykernel_21980\437325250.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Salary = df_s


Country Age    Salary  Purchased
0        0   1  0.685714          0
1        2   0  0.000000          1
2        1   0  0.171429          0
3        2   1  0.371429          0
5        0   0  0.285714          1
7        0   2  0.885714          1
8        1   2  1.000000          0
9        0   1  0.542857          1