In [442]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import scipy.stats as stats

In [443]:
iris = sns.load_dataset("iris")
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### <b>1. Kiểm định giả thuyết cho rằng chiều dài đài hoa trung bình của loài setosa là 5.0, độ rộng đài hoa versicolor là 3.5 và chiều dài cánh hoa của virginica là 1.4. Tiến hành kiểm định dựa trên tập mẫu gồm 25 dòng thông tin đầu tiên của mỗi loài hoa</b>

    - H0: Chiều dài đài hoa trung bình của loài setosa là 5.0
    - HA: Chiều dài đài hoa trung bình của loài setosa khác 5.0

- Chọn mức í nghĩa là 5%
-  Phương pháp kiểm định <b>One sample T-test</b>

In [444]:
setosa=iris[iris['species'].str.contains('setosa')]['sepal_length'][0:25]
setosa = np.array(setosa)
setosa

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8])

In [445]:
t_statistic, p_value = stats.ttest_1samp(a=setosa,popmean=5)
print('t_statistic',t_statistic)
print ('p_value',p_value)

t_statistic 0.3495270022268392
p_value 0.7297421135161855


In [446]:
if p_value > 0.05:
    print(f'Vì Pvalue = {p_value} > alpha = 0.05.\nH0 được chấp nhận: chiều dài trung bình đài hoa setosa là 5.0')
else:
        print(f'Vì Pvalue = {p_value} < alpha = 0.05.\nKhông đủ cơ sở để H0 được chấp nhận: chiều dài trung bình đài hoa setosa không phải là 5.0')

Vì Pvalue = 0.7297421135161855 > alpha = 0.05.
H0 được chấp nhận: chiều dài trung bình đài hoa setosa là 5.0


In [447]:
iris[iris['species'].str.contains('setosa')]['sepal_length'].mean()

5.006

    - H0: độ rộng đài hoa trung bình của loài versicolor là 3.5
    - HA: độ rộng đài hoa trung bình của loài versicolor khác 3.5

- Chọn mức í nghĩa là 5%
-  Phương pháp kiểm định <b>One sample T-test</b>

In [448]:
versicolor=iris[iris['species'].str.contains('versicolor')]['sepal_width'][0:25]
versicolor = np.array(versicolor)
versicolor

C:\Users\Admin-s\AppData\Local\Temp\ipykernel_4476\1525248993.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  versicolor=iris[iris['species'].str.contains('versicolor')]['sepal_width'][0:25]


array([3.2, 3.2, 3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2,
       2.9, 2.9, 3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9])

In [449]:
t_statistic, p_value = stats.ttest_1samp(a=versicolor,popmean=3.5)
print('t_statistic',t_statistic)
print ('p_value',p_value)

t_statistic -10.26356838593974
p_value 2.950231929091389e-10


In [450]:
if p_value > 0.05:
    print(f'Vì Pvalue = {p_value} > alpha = 0.05.\nH0 được chấp nhận: độ rộng đài hoa trung bình của loài versicolor là 3.5')
else:
        print(f'Vì Pvalue = {p_value} < alpha = 0.05.\nKhông đủ cơ sở để H0 được chấp nhận: độ rộng đài hoa trung bình của loài versicolor không phải 3.5')

Vì Pvalue = 2.950231929091389e-10 < alpha = 0.05.
Không đủ cơ sở để H0 được chấp nhận: độ rộng đài hoa trung bình của loài versicolor không phải 3.5


In [451]:
iris[iris['species'].str.contains('versicolor')]['sepal_width'].mean()

2.7700000000000005

    - H0: chiều dài cánh hoa trung bình của loài virginica là 1.4
    - HA: chiều dài cánh hoa trung bình của loài virginica khác 1.4

- Chọn mức í nghĩa là 5%
-  Phương pháp kiểm định <b>One sample T-test</b>

In [452]:
iris['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [453]:
verginica=iris[iris['species'].str.contains('virginica')]['petal_length'][0:25]
verginica = np.array(verginica)
verginica

C:\Users\Admin-s\AppData\Local\Temp\ipykernel_4476\54936209.py:1: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  verginica=iris[iris['species'].str.contains('virginica')]['petal_length'][0:25]


array([6. , 5.1, 5.9, 5.6, 5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5,
       5. , 5.1, 5.3, 5.5, 6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7])

In [454]:
t_statistic, p_value = stats.ttest_1samp(a=verginica,popmean=1.4)
print('t_statistic',t_statistic)
print ('p_value',p_value)

t_statistic 32.8101050594474
p_value 1.8843793148369172e-21


In [455]:
if p_value > 0.05:
    print(f'Vì Pvalue = {p_value} > alpha = 0.05.\nH0 được chấp nhận: chiều dài cánh hoa trung bình của loài verginica là 1.4')
else:
        print(f'Vì Pvalue = {p_value} < alpha = 0.05.\nKhông đủ cơ sở để H0 được chấp nhận: chiều dài cánh hoa trung bình của loài verginica không phải là 1.4')

Vì Pvalue = 1.8843793148369172e-21 < alpha = 0.05.
Không đủ cơ sở để H0 được chấp nhận: chiều dài cánh hoa trung bình của loài verginica không phải là 1.4


In [456]:
iris[iris['species'].str.contains('virginica')]['petal_length'].mean()

5.5520000000000005

### <b>2. Hãy kiểm định các giả thuyết cho rằng giá trị trung bình của chiều dài, độ rộng đài hoa, chiều dài, rộng cánh hoa của mỗi loài hoa hai vườn là bằng nhau </b>

##### Kiểm định giá trị trung bình của chiều dài mỗi loài hoa là bằng nhau

    - H0: Giá trị trung bình của chiều dài đài hoa mỗi loài là như nhau.
    - HA: Giá trị trung bình của chiều dài đài hoa mỗi loài có khác nhau.

- Chọn mức í nghĩa là 5%
-  Phương pháp kiểm định <b>Two sample T-test</b>

In [457]:
iris_ar = iris['species'].unique()
arr1 = []
arr2 = []
for i in iris_ar:
    ar=iris[iris['species'].str.contains(i)]['sepal_length'][0:25]
    arr1.append(np.array(ar))
    ar2=iris[iris['species'].str.contains(i)]['sepal_length'][25:51]
    arr2.append(np.array(ar2))


C:\Users\Admin-s\AppData\Local\Temp\ipykernel_4476\476134247.py:5: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  ar=iris[iris['species'].str.contains(i)]['sepal_length'][0:25]
C:\Users\Admin-s\AppData\Local\Temp\ipykernel_4476\476134247.py:7: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  ar2=iris[iris['species'].str.contains(i)]['sepal_length'][25:51]


In [458]:
arr1

[array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8]),
 array([7. , 6.4, 6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. ,
        6.1, 5.6, 6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4]),
 array([6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8,
        5.7, 5.8, 6.4, 6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7])]

In [459]:
arr2

[array([5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9,
        4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. ]),
 array([6.6, 6.8, 6.7, 6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3,
        5.6, 5.5, 5.5, 6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7]),
 array([7.2, 6.2, 6.1, 6.4, 7.2, 7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4,
        6. , 6.9, 6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])]

In [460]:
for i in range(len(arr1)):
    t_statistic, p_value = stats.ttest_ind(a= arr1[i],b=arr2[i],equal_var=True)
    if (p_value > 0.05):
        print(f'chiều dài trung bình đài hoa 2 vườn bằng nhau với loài hoa {iris_ar[i]} (pvalue = {p_value})')
    else:
        (print(f'chiều dài trung bình đài hoa  2 vườn khác nhau với loài hoa {iris_ar[i]} (pvalue = {p_value})'))

chiều dài trung bình đài hoa 2 vườn bằng nhau với loài hoa setosa (pvalue = 0.6635872571303114)
chiều dài trung bình đài hoa 2 vườn bằng nhau với loài hoa versicolor (pvalue = 0.3026126264579398)
chiều dài trung bình đài hoa 2 vườn bằng nhau với loài hoa virginica (pvalue = 0.8954597698813008)


Vậy giả thuyết H0: chiều dài trung bình đài hoa của 2 vườn là giống nhau với mỗi loài hoa là <b>chính xác</b>

### <b>3. Kiểm định giả thuyết cho rằng giá trị trung bình các thông tin của loài hoa này không phụ thuộc vào quá trình chăm sóc (Không sử dụng phân bón và sử dụng phân bón super-phosphate)</b>

    - H0: Giá trị trung bình của chiều dài đài hoa loài setosa là như nhau. khi sử dụng hoặc không sử dụng phân bón
    - HA: Giá trị trung bình của chiều dài đài hoa loài setosa có khác nhau khi sử dụng phân bón và không sử dụng phân bón.

- Chọn mức í nghĩa là 5% 
- phương pháp kiểm định Paired sample T-test

In [461]:
setosa_df = iris[iris['species'].str.contains('setosa')]
setosa_df.drop('species',axis=1,inplace=True)
setosa_df.head()

C:\Users\Admin-s\AppData\Local\Temp\ipykernel_4476\2054547486.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  setosa_df.drop('species',axis=1,inplace=True)


sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [462]:
_property = setosa_df.columns
_property

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [463]:
arr1 = []
arr2 = []
for i in _property:
    ar=setosa_df[i][0:25]
    arr1.append(np.array(ar))
    ar2=setosa_df[i][25:51]
    arr2.append(np.array(ar2))

In [464]:
arr1

[array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8]),
 array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4]),
 array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
        1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9]),
 array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
        0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2])]

In [465]:
# Có sử dụng phân bón
arr2

[array([5. , 5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9,
        4.4, 5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. ]),
 array([3. , 3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.6,
        3. , 3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3]),
 array([1.6, 1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4,
        1.3, 1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4]),
 array([0.2, 0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1,
        0.2, 0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2])]

In [466]:
for i in range(len(arr1)):
    t_statistic, p_value = stats.ttest_rel(a= arr1[i],b=arr2[i])
    if (p_value > 0.05):
        print(f'Giá trị trung bình của 2 phương pháp là giống nhau với thông số {_property[i]} (pvalue = {p_value})')
    else:
        print(f'Giá trị trung bình của 2 phương pháp là khác nhau với thông số {_property[i]} (pvalue = {p_value})')

Giá trị trung bình của 2 phương pháp là giống nhau với thông số sepal_length (pvalue = 0.6830857467767293)
Giá trị trung bình của 2 phương pháp là giống nhau với thông số sepal_width (pvalue = 0.38617205452294123)
Giá trị trung bình của 2 phương pháp là giống nhau với thông số petal_length (pvalue = 0.9314275194735182)
Giá trị trung bình của 2 phương pháp là giống nhau với thông số petal_width (pvalue = 0.8765788780036303)


Vậy H0 là chính xác. Các thông số của loài hòa setosa là <b>giống nhau</b> khi có sử dụng phân bón và không sử dụng phân bón. Vậy việc sử dụng phân bón không có ảnh hưởng tới các thông số của loài hoa này